name: Release

on:
    push:
        branches:
            - main
        tags-ignore:
            - '*'

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Configure node version
              uses: actions/setup-node@v3
              with:
                  node-version: 20
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Set write npm token
              run: |
                  npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"

            - name: Release
              if: github.ref == 'refs/heads/main'
              run: yarn semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
